### ISSUE TITLE
Change Browserify to Webpack

### ISSUE THREAD

**Issue by jk-gan** [jk-gan/ADM#1]
https://medium.com/@housecor/browserify-vs-webpack-b3d7ca08a0a9#.grke3h2qk
https://www.toptal.com/front-end/webpack-browserify-gulp-which-is-better

It seems like using Webpack is a better choice compare to Browserify.

**Comment by plwai** [comment]
Seems like Webpack is more structured than Browserify. Also, the simplicity of it makes me vote a point on it.
