### ISSUE TITLE
Change RPC websocket integration to C++ API integration

### ISSUE THREAD

**Issue by plwai** [jk-gan/ADM#12]
#7 RPC websocket integration seems like is vulnerable in term of security. The integration need to be redo. Thus, I proposes to use C++ API in this integration for a better security and performance as well.

**Comment by plwai** [comment]
@jk-gan Any idea about this issues? Should it be broken into smaller module?

**Comment by jk-gan** [comment]
Will figure it out when I finish #9

**Comment by plwai** [comment]
Okay. I will try to wrap c++ within nodejs first.

**Comment by plwai** [comment]
Now I have 2 options:

1. Make an C++ Api between aria and adm and compile using Nodejs Addon
2. Use Nodejs to make the Api by calling the dll

Which one is better?
@jk-gan

**Comment by plwai** [comment]
Compilation and Binding instructions updated in develop branch
