### ISSUE TITLE
React developer console in electron needed!!!

### ISSUE THREAD

**Issue by jk-gan** [jk-gan/ADM#13]
We need to have React Developer Tools in chromium (electron) DevTools to ease the React development process

**Comment by jk-gan** [comment]
https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md

**Comment by plwai** [comment]
That will be great if there is such thing in electron console. Just go ahead.

**Comment by jk-gan** [comment]
https://github.com/MarshallOfSound/electron-devtools-installer
https://github.com/firejune/electron-react-devtools

Which one do you prefer to?

**Comment by plwai** [comment]
Marshall got more star. haha
